. (Join-Path $PSScriptRoot 'Set-CandidateProfileV11.ps1')
$env:RENOVICE_LEGACY_UNCONDITIONAL_FOR_BREAK = '1'
$env:RENOVICE_CFG_PREFER_STRUCTURED_PLAIN = '1'
$env:RENOVICE_MULTIPLE_FORNPREP_ZERO_LIFETIMES = '1'
$env:RENOVICE_CANONICAL_EMPTY_OR_TRUTHINESS = '1'
$env:RENOVICE_NESTED_INDEX_RESULT_LIFETIMES = '1'
