. (Join-Path $PSScriptRoot 'Set-CandidateProfileV28.ps1')
$env:RENOVICE_CANONICAL_ROOT_REPEAT_RETURN_TAIL = '1'
$env:RENOVICE_CANONICAL_LATE_RETURNING_REPEAT_ARM = '1'
$env:RENOVICE_CFG_EXPANDED_GUARD_TERMINAL_RETRY = '1'
