. (Join-Path $PSScriptRoot 'Set-CandidateProfileV26.ps1')
$env:RENOVICE_CANONICAL_LEADING_REPEAT_GUARDS = '1'
$env:RENOVICE_CANONICAL_NESTED_RETURN_GUARDS = '1'
$env:RENOVICE_CANONICAL_RETURNING_REPEAT_ARM = '1'
