# Dot-source only for this explicitly labeled experimental profile.
$env:RENOVICE_CFG_INTERIOR_EXIT_WHILE = '1'
$env:RENOVICE_CFG_TRANSPARENT_LOOP_EXIT = '1'
$env:RENOVICE_CFG_PRIVATE_TAIL_RETURN_GUARD = '1'
$env:RENOVICE_CFG_INTERIOR_GUARD_CHAIN = '1'
$env:RENOVICE_CANONICAL_PREDICATE_ASSOCIATION = '1'
$env:RENOVICE_CANONICAL_INLINE_GUARD_CHAIN = '1'
$env:RENOVICE_CANONICAL_NIL_WHILE = '1'
$env:RENOVICE_CANONICAL_RETURN_ELSEIF = '1'
